# Generated by Django 3.2 on 2021-04-26 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0002_auto_20210426_1154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReqData',
            new_name='ReqDataModel',
        ),
    ]
