# Generated by Django 3.2 on 2021-04-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0004_auto_20210426_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='reqdatamodel',
            name='CollaboratorHomeInst',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reqdatamodel',
            name='CollaboratorName',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reqdatamodel',
            name='CollaboratorNationality',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reqdatamodel',
            name='EndDate',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reqdatamodel',
            name='Energy',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reqdatamodel',
            name='Flux',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reqdatamodel',
            name='Funded',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reqdatamodel',
            name='IonSpiecies',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reqdatamodel',
            name='LabSupportReq',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reqdatamodel',
            name='PreviousExp',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='reqdatamodel',
            name='ProjectTitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reqdatamodel',
            name='RequieredEquipment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reqdatamodel',
            name='Shifts',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reqdatamodel',
            name='SpecialRequirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reqdatamodel',
            name='SpecialSaftyPocedures',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reqdatamodel',
            name='SpokesPersonAdress',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reqdatamodel',
            name='SpokesPersonEmail',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reqdatamodel',
            name='SpokesPersonName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reqdatamodel',
            name='SpokesPersonPhonenumber',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reqdatamodel',
            name='StartDate',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reqdatamodel',
            name='Status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reqdatamodel',
            name='Summery',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reqdatamodel',
            name='PacRate',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='reqdatamodel',
            name='PartrecContactEmail',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reqdatamodel',
            name='PartrecContactName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reqdatamodel',
            name='ProjectCode',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
