# Generated by Django 3.2 on 2021-04-30 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0006_auto_20210429_1429'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReqDataModel',
            new_name='CreateReqModel',
        ),
    ]
