# Generated by Django 3.2 on 2021-04-30 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0007_rename_reqdatamodel_createreqmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createreqmodel',
            old_name='CollaboratorHomeInst',
            new_name='Collaborator_Home_Institute',
        ),
        migrations.RenameField(
            model_name='createreqmodel',
            old_name='CollaboratorName',
            new_name='Collaborator_Name',
        ),
        migrations.RenameField(
            model_name='createreqmodel',
            old_name='CollaboratorNationality',
            new_name='Collaborator_Nationality',
        ),
        migrations.RenameField(
            model_name='createreqmodel',
            old_name='EndDate',
            new_name='End_Date',
        ),
        migrations.RenameField(
            model_name='createreqmodel',
            old_name='IonSpiecies',
            new_name='Ion_Spiecies',
        ),
        migrations.RenameField(
            model_name='createreqmodel',
            old_name='LabSupportReq',
            new_name='Lab_Support_Requirements',
        ),
        migrations.RenameField(
            model_name='createreqmodel',
            old_name='PacRate',
            new_name='Pac_Rate',
        ),
        migrations.RenameField(
            model_name='createreqmodel',
            old_name='PartrecContactEmail',
            new_name='Partrec_Contact_Email',
        ),
        migrations.RenameField(
            model_name='createreqmodel',
            old_name='PartrecContactName',
            new_name='Partrec_Contact_Name',
        ),
        migrations.RenameField(
            model_name='createreqmodel',
            old_name='PreviousExp',
            new_name='Previous_Experiment',
        ),
        migrations.RenameField(
            model_name='createreqmodel',
            old_name='ProjectCode',
            new_name='Project_Code',
        ),
        migrations.RenameField(
            model_name='createreqmodel',
            old_name='ProjectTitle',
            new_name='Project_Title',
        ),
        migrations.RenameField(
            model_name='createreqmodel',
            old_name='RequieredEquipment',
            new_name='Requiered_Equipment',
        ),
        migrations.RenameField(
            model_name='createreqmodel',
            old_name='SpecialRequirements',
            new_name='Special_Requirements',
        ),
        migrations.RenameField(
            model_name='createreqmodel',
            old_name='SpecialSaftyPocedures',
            new_name='Special_Safty_Pocedures',
        ),
        migrations.RenameField(
            model_name='createreqmodel',
            old_name='SpokesPersonAdress',
            new_name='Spokesperson_Adress',
        ),
        migrations.RenameField(
            model_name='createreqmodel',
            old_name='SpokesPersonEmail',
            new_name='Spokesperson_Email',
        ),
        migrations.RenameField(
            model_name='createreqmodel',
            old_name='SpokesPersonName',
            new_name='Spokesperson_Name',
        ),
        migrations.RenameField(
            model_name='createreqmodel',
            old_name='SpokesPersonPhonenumber',
            new_name='Spokesperson_Phonenumber',
        ),
        migrations.RenameField(
            model_name='createreqmodel',
            old_name='StartDate',
            new_name='Start_Date',
        ),
    ]
