# Generated by Django 3.2 on 2021-05-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0008_auto_20210430_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createreqmodel',
            name='End_Date',
            field=models.DateTimeField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='createreqmodel',
            name='Start_Date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='createreqmodel',
            name='Status',
            field=models.CharField(choices=[('Select', 'Select an option'), ('Request', 'Request'), ('Tentavive', 'Tentative'), ('Accepted', 'Accepted'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Queued', 'Queued')], default='SELECT', max_length=100),
        ),
    ]
