# Generated by Django 3.2 on 2021-05-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0009_auto_20210504_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createreqmodel',
            name='Start_Date',
            field=models.DateTimeField(blank=True, max_length=20),
        ),
    ]
