# Generated by Django 3.2.3 on 2021-06-16 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beamrequest', '0032_alter_createbeamrequestmodel_funded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_file_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('Project_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beamrequest.createbeamrequestmodel')),
            ],
        ),
    ]
