# Generated by Django 3.2.3 on 2021-06-18 09:30

from django.db import migrations, models
import documentation.models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_alter_add_file_model_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_file_model',
            old_name='Project_Id',
            new_name='Project_Code',
        ),
        migrations.AlterField(
            model_name='add_file_model',
            name='file',
            field=models.FileField(upload_to=documentation.models.generate_path),
        ),
    ]
