# Generated by Django 3.2.3 on 2021-06-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0003_auto_20210618_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_file_model',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
