# Generated by Django 3.2 on 2021-05-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamrequest', '0003_alter_createbeamrequestmodel_shifts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createbeamrequestmodel',
            old_name='Ion_Spiecies',
            new_name='Ion_Species',
        ),
        migrations.RenameField(
            model_name='createbeamrequestmodel',
            old_name='Special_Safty_Pocedures',
            new_name='Special_Safty_Procedures',
        ),
        migrations.RenameField(
            model_name='createbeamrequestmodel',
            old_name='Summery',
            new_name='Summary',
        ),
        migrations.AlterField(
            model_name='createbeamrequestmodel',
            name='End_Date',
            field=models.DateTimeField(),
        ),
    ]
