# Generated by Django 3.2 on 2021-05-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamrequest', '0004_auto_20210510_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createbeamrequestmodel',
            name='End_Date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='createbeamrequestmodel',
            name='Shifts',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30)], default='1'),
        ),
        migrations.AlterField(
            model_name='createbeamrequestmodel',
            name='Start_Date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='createbeamrequestmodel',
            name='Status',
            field=models.CharField(choices=[('Select', 'Select an option'), ('Request', 'Request'), ('Tentavive', 'Tentative'), ('Accepted', 'Accepted'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Queued', 'Queued')], default='SELECT', max_length=25),
        ),
    ]
