# Generated by Django 3.2 on 2021-05-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamrequest', '0005_auto_20210510_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='createbeamrequestmodel',
            name='test',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
