# Generated by Django 3.2 on 2021-05-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beamrequest', '0006_createbeamrequestmodel_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createbeamrequestmodel',
            name='test',
        ),
    ]
