# Generated by Django 3.2 on 2021-05-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamrequest', '0009_alter_createbeamrequestmodel_ion_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createbeamrequestmodel',
            name='Energy',
            field=models.CharField(choices=[('Select', 'Select Ion species'), ('P', 'Protons'), ('4He', 'Helium'), ('12C', 'Carbon')], default='SELECT', max_length=20),
        ),
    ]
