# Generated by Django 3.2 on 2021-05-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamrequest', '0010_alter_createbeamrequestmodel_energy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createbeamrequestmodel',
            name='Energy',
            field=models.CharField(choices=[('Select', 'Select Ion species'), ('90 MeV', '90MeV'), ('150 MeV', '150 MeV'), ('190 MeV', '190 MeV')], default='SELECT', max_length=20),
        ),
        migrations.AlterField(
            model_name='createbeamrequestmodel',
            name='Ion_Species',
            field=models.CharField(choices=[('Select', 'Select Ion species'), ('90 MeV', '90MeV'), ('150 MeV', '150 MeV'), ('190 MeV', '190 MeV')], default='SELECT', max_length=20),
        ),
    ]
