# Generated by Django 3.2 on 2021-05-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamrequest', '0011_auto_20210512_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='createbeamrequestmodel',
            name='Different_Beams',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default='1'),
        ),
        migrations.AlterField(
            model_name='createbeamrequestmodel',
            name='Energy',
            field=models.CharField(choices=[('Select', 'Select Energy'), ('90 MeV', '90MeV'), ('150 MeV', '150 MeV'), ('190 MeV', '190 MeV')], default='SELECT', max_length=20),
        ),
        migrations.AlterField(
            model_name='createbeamrequestmodel',
            name='Ion_Species',
            field=models.CharField(choices=[('Select', 'Select Ion species'), ('P', 'Protons'), ('4He', 'Helium'), ('12C', 'Carbon')], default='SELECT', max_length=20),
        ),
        migrations.AlterField(
            model_name='createbeamrequestmodel',
            name='Shifts',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16)], default='1'),
        ),
    ]
