# Generated by Django 3.2.3 on 2021-05-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamrequest', '0012_auto_20210515_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createbeamrequestmodel',
            name='Ion_Species',
            field=models.CharField(choices=[('Select', 'Select Ion species'), ('H', 'H or P'), ('He', 'He'), ('Li', 'Li'), ('B', 'B'), ('C', 'C'), ('N', 'N'), ('O', 'O'), ('F', 'F'), ('Ne', 'Ne'), ('Na', 'Na'), ('Mg', 'Mg'), ('Ar', 'Ar'), ('Ca', 'Ca'), ('Kr', 'Kr'), ('Xe', 'Xe'), ('Pb', 'Pb')], default='SELECT', max_length=20),
        ),
    ]
