# Generated by Django 3.2.3 on 2021-05-20 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beamrequest', '0013_alter_createbeamrequestmodel_ion_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='IonSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='createbeamrequestmodel',
            name='Different_Beams',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default='1'),
        ),
        migrations.CreateModel(
            name='Energys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Energys', models.CharField(max_length=50)),
                ('Ion_Species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beamrequest.ionspecies')),
            ],
        ),
        migrations.AlterField(
            model_name='createbeamrequestmodel',
            name='Energy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beamrequest.energys'),
        ),
        migrations.AlterField(
            model_name='createbeamrequestmodel',
            name='Ion_Species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beamrequest.ionspecies'),
        ),
    ]
