# Generated by Django 3.2.3 on 2021-05-20 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beamrequest', '0014_auto_20210520_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energys',
            old_name='Energys',
            new_name='name',
        ),
    ]
