# Generated by Django 3.2.3 on 2021-05-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beamrequest', '0015_rename_energys_energys_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energys',
            old_name='Ion_Species',
            new_name='Ion_Species_id',
        ),
    ]
