# Generated by Django 3.2.3 on 2021-05-27 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beamrequest', '0016_rename_ion_species_energys_ion_species_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energys',
            old_name='Ion_Species_id',
            new_name='Ion_Species',
        ),
    ]
