# Generated by Django 3.2.3 on 2021-05-27 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beamrequest', '0017_rename_ion_species_id_energys_ion_species'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energys',
            old_name='Ion_Species',
            new_name='Ion_Species_id',
        ),
    ]
