# Generated by Django 3.2.3 on 2021-05-29 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beamrequest', '0019_rename_ion_species_id_energys_ion_species'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energys',
            old_name='name',
            new_name='energy',
        ),
        migrations.RenameField(
            model_name='ionspecies',
            old_name='name',
            new_name='ionspecie',
        ),
    ]
