# Generated by Django 3.2.3 on 2021-06-01 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beamrequest', '0022_auto_20210601_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energys',
            old_name='Energy',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='ionspecies',
            old_name='Ion_Species',
            new_name='Name',
        ),
    ]
