# Generated by Django 3.2.3 on 2021-06-03 09:49

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('beamrequest', '0024_alter_createbeamrequestmodel_ion_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createbeamrequestmodel',
            name='End_Date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='createbeamrequestmodel',
            name='Energy',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='Ion_Species', chained_model_field='Ion_Species', null=True, on_delete=django.db.models.deletion.CASCADE, to='beamrequest.energys'),
        ),
        migrations.AlterField(
            model_name='createbeamrequestmodel',
            name='Ion_Species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beamrequest.ionspecies'),
        ),
        migrations.AlterField(
            model_name='createbeamrequestmodel',
            name='Start_Date',
            field=models.DateField(blank=True),
        ),
    ]
