# Generated by Django 3.2.3 on 2021-06-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamrequest', '0026_auto_20210603_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createbeamrequestmodel',
            name='End_Date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='createbeamrequestmodel',
            name='Start_Date',
            field=models.DateTimeField(blank=True),
        ),
    ]
