# Generated by Django 3.2.3 on 2021-06-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamrequest', '0029_auto_20210605_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createbeamrequestmodel',
            name='Flux',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
