# Generated by Django 3.2.3 on 2021-06-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamrequest', '0032_alter_createbeamrequestmodel_funded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createbeamrequestmodel',
            name='Shifts',
        ),
        migrations.AddField(
            model_name='createbeamrequestmodel',
            name='Hours',
            field=models.IntegerField(default='1'),
        ),
    ]
