# Generated by Django 3.2.3 on 2021-10-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamrequest', '0034_auto_20211019_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='createbeamrequestmodel',
            name='Different_Beams',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default='1'),
        ),
    ]
