# Generated by Django 3.2.3 on 2021-10-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamrequest', '0036_auto_20211022_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='createbeamrequestmodel',
            name='Beam_Note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='createbeamrequestmodel',
            name='Different_Beams',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default='1'),
        ),
    ]
