# Generated by Django 3.2.3 on 2021-11-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamrequest', '0037_auto_20211026_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energys',
            name='Name',
            field=models.CharField(max_length=10),
        ),
    ]
