# Generated by Django 3.2.3 on 2021-11-23 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beamrequest', '0038_alter_energys_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createbeamrequestmodel',
            name='Different_Beams',
        ),
    ]
