# Generated by Django 3.2.3 on 2021-12-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamrequest', '0040_auto_20211201_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createbeamrequestmodel',
            name='calibration',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='createbeamrequestmodel',
            name='cryo_error',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='createbeamrequestmodel',
            name='defelopment',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='createbeamrequestmodel',
            name='emc1_error',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='createbeamrequestmodel',
            name='foeldi_error',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='createbeamrequestmodel',
            name='general_error',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='createbeamrequestmodel',
            name='other_error',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='createbeamrequestmodel',
            name='planned',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='createbeamrequestmodel',
            name='rf_error',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='createbeamrequestmodel',
            name='unused',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='createbeamrequestmodel',
            name='woak',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
    ]
