# Generated by Django 3.2.3 on 2021-12-05 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beamrequest', '0040_auto_20211205_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energys',
            old_name='Ion_Species',
            new_name='ion_species',
        ),
        migrations.RenameField(
            model_name='energys',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ionspecies',
            old_name='Name',
            new_name='name',
        ),
    ]
