# Generated by Django 3.2.3 on 2021-12-05 12:44

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('beamrequest', '0041_auto_20211205_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createbeamrequestmodel',
            name='energy',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='ion_species', chained_model_field='ion_species', null=True, on_delete=django.db.models.deletion.CASCADE, to='beamrequest.energys'),
        ),
    ]
