# Generated by Django 3.2.3 on 2021-12-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamrequest', '0043_rename_createbeamrequestmodel_beamrequestmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='beamrequestmodel',
            name='Different_Beams',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default='1'),
        ),
    ]
