# Generated by Django 3.2.3 on 2021-06-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0002_auto_20210625_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hourregistrationmodel',
            old_name='Beam',
            new_name='Beam_Friday',
        ),
        migrations.RenameField(
            model_name='hourregistrationmodel',
            old_name='Source',
            new_name='Beam_Monday',
        ),
        migrations.RemoveField(
            model_name='hourregistrationmodel',
            name='Day',
        ),
        migrations.AddField(
            model_name='hourregistrationmodel',
            name='Beam_Saturday',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hourregistrationmodel',
            name='Beam_Sunday',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hourregistrationmodel',
            name='Beam_Thursday',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hourregistrationmodel',
            name='Beam_Tuesday',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hourregistrationmodel',
            name='Beam_Wednesday',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hourregistrationmodel',
            name='Source_Friday',
            field=models.CharField(choices=[('Select', 'Select a source'), ('CUSP', 'CUSP'), ('AECR', 'AECR'), ('SNG', 'SNG')], default='SELECT', max_length=25),
        ),
        migrations.AddField(
            model_name='hourregistrationmodel',
            name='Source_Monday',
            field=models.CharField(choices=[('Select', 'Select a source'), ('CUSP', 'CUSP'), ('AECR', 'AECR'), ('SNG', 'SNG')], default='SELECT', max_length=25),
        ),
        migrations.AddField(
            model_name='hourregistrationmodel',
            name='Source_Saterday',
            field=models.CharField(choices=[('Select', 'Select a source'), ('CUSP', 'CUSP'), ('AECR', 'AECR'), ('SNG', 'SNG')], default='SELECT', max_length=25),
        ),
        migrations.AddField(
            model_name='hourregistrationmodel',
            name='Source_Sunday',
            field=models.CharField(choices=[('Select', 'Select a source'), ('CUSP', 'CUSP'), ('AECR', 'AECR'), ('SNG', 'SNG')], default='SELECT', max_length=25),
        ),
        migrations.AddField(
            model_name='hourregistrationmodel',
            name='Source_Thursday',
            field=models.CharField(choices=[('Select', 'Select a source'), ('CUSP', 'CUSP'), ('AECR', 'AECR'), ('SNG', 'SNG')], default='SELECT', max_length=25),
        ),
        migrations.AddField(
            model_name='hourregistrationmodel',
            name='Source_Tuesday',
            field=models.CharField(choices=[('Select', 'Select a source'), ('CUSP', 'CUSP'), ('AECR', 'AECR'), ('SNG', 'SNG')], default='SELECT', max_length=25),
        ),
        migrations.AddField(
            model_name='hourregistrationmodel',
            name='Source_Wednesday',
            field=models.CharField(choices=[('Select', 'Select a source'), ('CUSP', 'CUSP'), ('AECR', 'AECR'), ('SNG', 'SNG')], default='SELECT', max_length=25),
        ),
        migrations.AlterField(
            model_name='hourregistrationmodel',
            name='Day_Shift_Monday',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
