# Generated by Django 3.2.3 on 2021-06-30 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0003_auto_20210627_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day_Shift', models.CharField(blank=True, max_length=50, null=True)),
                ('Evening_Shift', models.CharField(blank=True, max_length=50, null=True)),
                ('Night_Shift', models.CharField(blank=True, max_length=50, null=True)),
                ('Beam', models.CharField(blank=True, max_length=50, null=True)),
                ('Source', models.CharField(choices=[('Select', 'Select a source'), ('CUSP', 'CUSP'), ('AECR', 'AECR'), ('SNG', 'SNG')], default='SELECT', max_length=25)),
                ('Customer', models.CharField(blank=True, max_length=50, null=True)),
                ('Prjoect_Code', models.CharField(blank=True, max_length=50, null=True)),
                ('Scheduled_Hours', models.CharField(blank=True, max_length=50, null=True)),
                ('Delivered_Hours', models.CharField(blank=True, max_length=50, null=True)),
                ('No_Operators', models.CharField(blank=True, max_length=50, null=True)),
                ('Notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='hourregistrationmodel',
            name='Week',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52)], default=26),
        ),
        migrations.AddField(
            model_name='hourregistrationmodel',
            name='Monday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hours.monday'),
        ),
    ]
