# Generated by Django 3.2.3 on 2021-07-02 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0005_auto_20210702_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day_Shift', models.CharField(blank=True, max_length=50, null=True)),
                ('Evening_Shift', models.CharField(blank=True, max_length=50, null=True)),
                ('Night_Shift', models.CharField(blank=True, max_length=50, null=True)),
                ('Beam', models.CharField(blank=True, max_length=50, null=True)),
                ('Source', models.CharField(choices=[('Select', 'Select a source'), ('CUSP', 'CUSP'), ('AECR', 'AECR'), ('SNG', 'SNG')], default='SELECT', max_length=25)),
                ('Customer', models.CharField(blank=True, max_length=50, null=True)),
                ('Prjoect_Code', models.CharField(blank=True, max_length=50, null=True)),
                ('Scheduled_Hours', models.CharField(blank=True, max_length=50, null=True)),
                ('Delivered_Hours', models.CharField(blank=True, max_length=50, null=True)),
                ('No_Operators', models.CharField(blank=True, max_length=50, null=True)),
                ('Notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Saturday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day_Shift', models.CharField(blank=True, max_length=50, null=True)),
                ('Evening_Shift', models.CharField(blank=True, max_length=50, null=True)),
                ('Night_Shift', models.CharField(blank=True, max_length=50, null=True)),
                ('Beam', models.CharField(blank=True, max_length=50, null=True)),
                ('Source', models.CharField(choices=[('Select', 'Select a source'), ('CUSP', 'CUSP'), ('AECR', 'AECR'), ('SNG', 'SNG')], default='SELECT', max_length=25)),
                ('Customer', models.CharField(blank=True, max_length=50, null=True)),
                ('Prjoect_Code', models.CharField(blank=True, max_length=50, null=True)),
                ('Scheduled_Hours', models.CharField(blank=True, max_length=50, null=True)),
                ('Delivered_Hours', models.CharField(blank=True, max_length=50, null=True)),
                ('No_Operators', models.CharField(blank=True, max_length=50, null=True)),
                ('Notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sunday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day_Shift', models.CharField(blank=True, max_length=50, null=True)),
                ('Evening_Shift', models.CharField(blank=True, max_length=50, null=True)),
                ('Night_Shift', models.CharField(blank=True, max_length=50, null=True)),
                ('Beam', models.CharField(blank=True, max_length=50, null=True)),
                ('Source', models.CharField(choices=[('Select', 'Select a source'), ('CUSP', 'CUSP'), ('AECR', 'AECR'), ('SNG', 'SNG')], default='SELECT', max_length=25)),
                ('Customer', models.CharField(blank=True, max_length=50, null=True)),
                ('Prjoect_Code', models.CharField(blank=True, max_length=50, null=True)),
                ('Scheduled_Hours', models.CharField(blank=True, max_length=50, null=True)),
                ('Delivered_Hours', models.CharField(blank=True, max_length=50, null=True)),
                ('No_Operators', models.CharField(blank=True, max_length=50, null=True)),
                ('Notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thursday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day_Shift', models.CharField(blank=True, max_length=50, null=True)),
                ('Evening_Shift', models.CharField(blank=True, max_length=50, null=True)),
                ('Night_Shift', models.CharField(blank=True, max_length=50, null=True)),
                ('Beam', models.CharField(blank=True, max_length=50, null=True)),
                ('Source', models.CharField(choices=[('Select', 'Select a source'), ('CUSP', 'CUSP'), ('AECR', 'AECR'), ('SNG', 'SNG')], default='SELECT', max_length=25)),
                ('Customer', models.CharField(blank=True, max_length=50, null=True)),
                ('Prjoect_Code', models.CharField(blank=True, max_length=50, null=True)),
                ('Scheduled_Hours', models.CharField(blank=True, max_length=50, null=True)),
                ('Delivered_Hours', models.CharField(blank=True, max_length=50, null=True)),
                ('No_Operators', models.CharField(blank=True, max_length=50, null=True)),
                ('Notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wednesday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day_Shift', models.CharField(blank=True, max_length=50, null=True)),
                ('Evening_Shift', models.CharField(blank=True, max_length=50, null=True)),
                ('Night_Shift', models.CharField(blank=True, max_length=50, null=True)),
                ('Beam', models.CharField(blank=True, max_length=50, null=True)),
                ('Source', models.CharField(choices=[('Select', 'Select a source'), ('CUSP', 'CUSP'), ('AECR', 'AECR'), ('SNG', 'SNG')], default='SELECT', max_length=25)),
                ('Customer', models.CharField(blank=True, max_length=50, null=True)),
                ('Prjoect_Code', models.CharField(blank=True, max_length=50, null=True)),
                ('Scheduled_Hours', models.CharField(blank=True, max_length=50, null=True)),
                ('Delivered_Hours', models.CharField(blank=True, max_length=50, null=True)),
                ('No_Operators', models.CharField(blank=True, max_length=50, null=True)),
                ('Notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='hourregistrationmodel',
            name='Friday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hours.friday'),
        ),
        migrations.AddField(
            model_name='hourregistrationmodel',
            name='Saturday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hours.saturday'),
        ),
        migrations.AddField(
            model_name='hourregistrationmodel',
            name='Sunday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hours.sunday'),
        ),
        migrations.AddField(
            model_name='hourregistrationmodel',
            name='Thursday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hours.thursday'),
        ),
        migrations.AddField(
            model_name='hourregistrationmodel',
            name='Wednesday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hours.wednesday'),
        ),
    ]
