# Generated by Django 3.2.3 on 2021-07-07 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0008_auto_20210706_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourregistrationmodel',
            name='Tuesday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hours.tuesday'),
        ),
    ]
