# Generated by Django 3.2.3 on 2021-07-08 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0009_hourregistrationmodel_tuesday'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourregistrationmodel',
            name='Wednesday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hours.wednesday'),
        ),
    ]
