# Generated by Django 3.2.3 on 2021-07-10 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beamrequest', '0033_auto_20210621_2218'),
        ('hours', '0010_hourregistrationmodel_wednesday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friday',
            name='Beam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beamrequest.ionspecies'),
        ),
        migrations.AlterField(
            model_name='friday',
            name='Prjoect_Code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beamrequest.createbeamrequestmodel'),
        ),
        migrations.AlterField(
            model_name='saturday',
            name='Beam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beamrequest.ionspecies'),
        ),
        migrations.AlterField(
            model_name='saturday',
            name='Prjoect_Code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beamrequest.createbeamrequestmodel'),
        ),
        migrations.AlterField(
            model_name='sunday',
            name='Beam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beamrequest.ionspecies'),
        ),
        migrations.AlterField(
            model_name='sunday',
            name='Prjoect_Code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beamrequest.createbeamrequestmodel'),
        ),
        migrations.AlterField(
            model_name='thursday',
            name='Beam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beamrequest.ionspecies'),
        ),
        migrations.AlterField(
            model_name='thursday',
            name='Prjoect_Code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beamrequest.createbeamrequestmodel'),
        ),
        migrations.AlterField(
            model_name='tuesday',
            name='Beam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beamrequest.ionspecies'),
        ),
        migrations.AlterField(
            model_name='tuesday',
            name='Prjoect_Code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beamrequest.createbeamrequestmodel'),
        ),
        migrations.AlterField(
            model_name='wednesday',
            name='Beam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beamrequest.ionspecies'),
        ),
        migrations.AlterField(
            model_name='wednesday',
            name='Prjoect_Code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beamrequest.createbeamrequestmodel'),
        ),
    ]
