# Generated by Django 3.2.3 on 2021-07-10 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0016_auto_20210710_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friday',
            name='Week',
        ),
        migrations.RemoveField(
            model_name='friday',
            name='Year',
        ),
        migrations.RemoveField(
            model_name='monday',
            name='Week',
        ),
        migrations.RemoveField(
            model_name='monday',
            name='Year',
        ),
        migrations.RemoveField(
            model_name='saturday',
            name='Week',
        ),
        migrations.RemoveField(
            model_name='saturday',
            name='Year',
        ),
        migrations.RemoveField(
            model_name='sunday',
            name='Week',
        ),
        migrations.RemoveField(
            model_name='sunday',
            name='Year',
        ),
        migrations.RemoveField(
            model_name='thursday',
            name='Week',
        ),
        migrations.RemoveField(
            model_name='thursday',
            name='Year',
        ),
        migrations.RemoveField(
            model_name='tuesday',
            name='Week',
        ),
        migrations.RemoveField(
            model_name='tuesday',
            name='Year',
        ),
        migrations.RemoveField(
            model_name='wednesday',
            name='Week',
        ),
        migrations.RemoveField(
            model_name='wednesday',
            name='Year',
        ),
        migrations.AlterField(
            model_name='friday',
            name='Source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hours.source'),
        ),
        migrations.AlterField(
            model_name='monday',
            name='Day_Shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hours.operators'),
        ),
        migrations.AlterField(
            model_name='saturday',
            name='Source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hours.source'),
        ),
        migrations.AlterField(
            model_name='sunday',
            name='Source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hours.source'),
        ),
        migrations.AlterField(
            model_name='thursday',
            name='Source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hours.source'),
        ),
        migrations.AlterField(
            model_name='tuesday',
            name='Source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hours.source'),
        ),
        migrations.AlterField(
            model_name='wednesday',
            name='Source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hours.source'),
        ),
    ]
