# Generated by Django 3.2.3 on 2021-07-10 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0017_auto_20210710_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monday',
            name='Day_Shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Monday_Day_Shift', to='hours.operators'),
        ),
        migrations.AlterField(
            model_name='monday',
            name='Evening_Shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Monday_Evening_Shift', to='hours.operators'),
        ),
        migrations.AlterField(
            model_name='monday',
            name='Night_Shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Monday_Night_Shift', to='hours.operators'),
        ),
        migrations.AlterField(
            model_name='tuesday',
            name='Day_Shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tuesday_Day_Shift', to='hours.operators'),
        ),
    ]
