# Generated by Django 3.2.3 on 2021-07-17 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0019_auto_20210717_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='No_Operators',
        ),
    ]
