# Generated by Django 3.2.3 on 2021-07-20 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0021_auto_20210720_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='Week',
        ),
        migrations.RemoveField(
            model_name='day',
            name='Year',
        ),
    ]
