# Generated by Django 3.2.3 on 2021-07-20 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0022_auto_20210720_0848'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HourReg',
            new_name='HourRegModel',
        ),
    ]
