# Generated by Django 3.2.3 on 2021-10-28 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beamrequest', '0037_auto_20211026_1750'),
        ('hours', '0026_auto_20211028_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourregistrationmodel',
            name='hours',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hourregistrationmodel',
            name='project_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beamrequest.createbeamrequestmodel'),
        ),
        migrations.AlterField(
            model_name='hourregistrationmodel',
            name='calibration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hourregistrationmodel',
            name='cryo_error',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hourregistrationmodel',
            name='defelopment',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hourregistrationmodel',
            name='emc1_error',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hourregistrationmodel',
            name='foeldi_error',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hourregistrationmodel',
            name='general_error',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hourregistrationmodel',
            name='other_error',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hourregistrationmodel',
            name='planned',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hourregistrationmodel',
            name='rf_error',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hourregistrationmodel',
            name='unused',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hourregistrationmodel',
            name='woak',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
