# Generated by Django 3.2.3 on 2021-10-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0027_auto_20211028_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hourregistrationmodel',
            old_name='hours',
            new_name='hours_deliverd',
        ),
        migrations.AddField(
            model_name='hourregistrationmodel',
            name='hours_requested',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
