# Generated by Django 3.2.3 on 2021-12-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0036_auto_20211206_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourregistrationmodel',
            name='hours_deliverd',
        ),
    ]
