# Generated by Django 3.2.3 on 2021-12-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0038_hourregistrationmodel_hours_deliverd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hourregistrationmodel',
            old_name='defelopment',
            new_name='development',
        ),
        migrations.RemoveField(
            model_name='hourregistrationmodel',
            name='hours_deliverd',
        ),
        migrations.RemoveField(
            model_name='hourregistrationmodel',
            name='month',
        ),
        migrations.AlterField(
            model_name='hourregistrationmodel',
            name='day',
            field=models.CharField(choices=[('Select', 'Select a day'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='SELECT', max_length=25),
        ),
    ]
