# Generated by Django 3.2.3 on 2021-12-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0039_auto_20211207_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourregistrationmodel',
            name='calibration',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='hourregistrationmodel',
            name='cryo_error',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='hourregistrationmodel',
            name='development',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='hourregistrationmodel',
            name='emc1_error',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='hourregistrationmodel',
            name='foeldi_error',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='hourregistrationmodel',
            name='general_error',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='hourregistrationmodel',
            name='other_error',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='hourregistrationmodel',
            name='planned',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='hourregistrationmodel',
            name='rf_error',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='hourregistrationmodel',
            name='unused',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='hourregistrationmodel',
            name='woak',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
