# Generated by Django 3.2.3 on 2022-01-17 12:23

import django.core.validators
from django.db import migrations, models
import hours.models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0040_auto_20211207_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourregistrationmodel',
            name='hours_deliverd',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='hourregistrationmodel',
            name='week',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52)], default=3),
        ),
        migrations.AlterField(
            model_name='hourregistrationmodel',
            name='year',
            field=models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(2020), hours.models.max_value_current_year]),
        ),
    ]
